### ISSUE TITLE
Locality 

### ISSUE THREAD

**Issue by stephanenicolas** [tumblr/Remember#1]
Would it be possible to create local stores as the shared prefs do ?

This would be useful in large apps to prevent creating a large static shared data structure where every can play with the state of the app. That can quickly lead to a ball of mud anti-pattern implementation.

**Comment by mlapadula** [comment]
Ah, we currently get the same functionality by namespacing the keys rather than the files. So Remember works off of one file, but individual classes store/retrieve data prefixed by "com.myclass.whatever".

Think of it like the way you'd use Redis (or whatever key-value store you prefer) on a server: you may have only one process, but by namespacing keys you don't have to maintain separate files or instances of the store.
