### ISSUE TITLE
"Guava" is a huge library, could you extract the usage code?

### ISSUE THREAD

**Issue by mrfanr** [tumblr/Remember#4]

**Comment by Shusshu** [comment]
+1

**Comment by tasomaniac** [comment]
+1 for this.

**Comment by vijayrawatsan** [comment]
Somebody just did.. 
https://github.com/tumblr/Remember/pull/12

**Comment by mlapadula** [comment]
Cool -- didn't realize people would have objections to Guava since we use it internally a bunch, but that makes sense to me.

The way I see it, the main advantage of Guava is that we can use their Function class and be compatible with other Guava utilities/classes/etc. Also it's pretty widely used, and anything you don't use can be stripped out with ProGuard.

**Comment by mlapadula** [comment]
Merged that PR, we should be good now. Happy hacking :)
